version: '3.8'
services:
  buys:
    restart: always
    build:
      context: ./backend/buys
      dockerfile: Dockerfile
    environment:
      - LANGUAGE=RU
    command: uvicorn buys:buys --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    links:
      - db
  shops:
    restart: always
    build:
      context: ./backend/shops
      dockerfile: Dockerfile
    command: uvicorn shops:shops --reload --host 0.0.0.0 --port 5000
    environment:
      - LANGUAGE=RU
    ports:
      - 5000:5000
    links:
      - db
  db:
    image: postgres:13.0
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backend_rtu
      - POSTGRES_PORT=5432
    expose:
      - 5432
volumes:
    postgres_data: